[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_egui = { workspace = true }
bevy_framepace = { workspace = true }
shared = { path = "../shared" }
