[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
shared = { path = "../shared" }
physics = { path = "../physics" }
map = { path = "../map" }
